-- Phase 4 schema extensions
ALTER TABLE projects ADD COLUMN IF NOT EXISTS category VARCHAR(100) DEFAULT 'General';

ALTER TABLE settings ADD COLUMN IF NOT EXISTS hero_subtitle TEXT;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS secondary_color VARCHAR(50) DEFAULT '#6366F1';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS seo_meta_title VARCHAR(255);
ALTER TABLE settings ADD COLUMN IF NOT EXISTS seo_description TEXT;

ALTER TABLE blogs ADD COLUMN IF NOT EXISTS excerpt TEXT DEFAULT '';

ALTER TABLE contact_messages ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE social_links ADD COLUMN IF NOT EXISTS display_order INTEGER DEFAULT 0;

ALTER TABLE resumes ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
