ALTER TABLE users
ADD COLUMN IF NOT EXISTS career_objective TEXT,
ADD COLUMN IF NOT EXISTS location VARCHAR(150),
ADD COLUMN IF NOT EXISTS city VARCHAR(100),
ADD COLUMN IF NOT EXISTS country VARCHAR(100),
ADD COLUMN IF NOT EXISTS google_map_link TEXT,
ADD COLUMN IF NOT EXISTS google_map_embed TEXT;
